---
title: "03_clustering_LCP"
output: html_document
---

```{r setup}
# on fait en sorte que le wd soit bon aussi quand on exécute chunk by chunk
if (interactive()) {
  setwd(rprojroot::find_rstudio_root_file())
}
```
```{r, include=FALSE}}
# chargement des librairies
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(openair)
library(foehnix)
# paramètres pour l'exécution du code
savefig = TRUE
figpath <- "./outputs/figures/clustering_LCP/"
```
```{r}
# chargement des functions
source("./R/functions/clustering_functions.R")
```
# Chargement des données
```{r}
#load data
meteoCO2 <- readRDS("./data/processed/df_meteoCO2_LCP.rds")

# on supprime les lignes où on a des na
meteoCO2 <- meteoCO2 %>%
  filter(!is.na(t2m) & !is.na(relative_humidity) & 
           !is.na(surfacepressure) & !is.na(ssrd) & 
           !is.na(windu) & !is.na(windv) & 
           !is.na(totalprecipitation) & !is.na(wd) & !is.na(ws) & !is.na(CO2_dry_corr_cal))

# dates de début et de fin
print(paste("Date début:", min(meteoCO2$date)))
print(paste("Date fin:", max(meteoCO2$date)))

# nombre de jours où on a au moins une ligne
print(paste("Nombre de jours:", n_distinct(as.Date(meteoCO2$date))))
```

# Désaisonnalisation
```{r}
# variables à désaisonnaliser
vars_to_deseasonalize <- c("CO2_dry_corr_cal", "t2m")
# ajout de time (temps en années pour la régression)
meteoCO2 <- meteoCO2 %>%
  mutate(time = as.numeric(difftime(date, min(date), units = "days")) / 365.25)
# désaisonnalisation
res <- fit_regression_multi(meteoCO2, vars_to_deseasonalize, trend = TRUE)
meteoCO2 <- res$data
coeffs_reg <- res$models
```

```{r}
meteoCO2_DJF <- meteoCO2 %>%
  filter(saison == "DJF")
```
# préparation des données pour le clustering
## moyennes par jour/plage
```{r}
vars_to_mean <- c("CO2_dry_corr_cal", "t2m", "relative_humidity", 
                        "surfacepressure", "ssrd", "windu", "windv", "ablh")
vars_to_sum <- c("totalprecipitation")
meteoCO2$day <- as.Date(meteoCO2$date)
meteoCO2_DJF$day <- as.Date(meteoCO2_DJF$date)

meteoCO2_mean <- meteoCO2 %>%
  group_by(day) %>%
  summarise(across(all_of(vars_to_mean), \(x) mean(x, na.rm = TRUE)),
            across(all_of(vars_to_sum), \(x) sum(x, na.rm = TRUE))) %>%
  ungroup()

meteoCO2_mean_DJF <- meteoCO2_DJF %>%
  group_by(day) %>%
  summarise(across(all_of(vars_to_mean), \(x) mean(x, na.rm = TRUE)),
            across(all_of(vars_to_sum), \(x) sum(x, na.rm = TRUE))) %>%
  ungroup()

# matin/soir
meteoCO2_mean_matin <- meteoCO2 %>%
  filter(flag_dn == "matin") %>%
  group_by(day) %>%
  summarise(across(all_of(vars_to_mean), \(x) mean(x, na.rm = TRUE)),
            across(all_of(vars_to_sum), \(x) sum(x, na.rm = TRUE))) %>%
  ungroup()

meteoCO2_mean_soir <- meteoCO2 %>%
  filter(flag_dn == "soir") %>%
  group_by(day) %>%
  summarise(across(all_of(vars_to_mean), \(x) mean(x, na.rm = TRUE)),
            across(all_of(vars_to_sum), \(x) sum(x, na.rm = TRUE))) %>%
  ungroup()
# matin/soir DJF
meteoCO2_mean_matin_DJF <- meteoCO2_DJF %>%
  filter(flag_dn == "matin") %>%
  group_by(day) %>%
  summarise(across(all_of(vars_to_mean), \(x) mean(x, na.rm = TRUE)),
            across(all_of(vars_to_sum), \(x) sum(x, na.rm = TRUE))) %>%
  ungroup()
meteoCO2_mean_soir_DJF <- meteoCO2_DJF %>%
  filter(flag_dn == "soir") %>%
  group_by(day) %>%
  summarise(across(all_of(vars_to_mean), \(x) mean(x, na.rm = TRUE)),
            across(all_of(vars_to_sum), \(x) sum(x, na.rm = TRUE))) %>%
  ungroup()
rm(meteoCO2, meteoCO2_DJF)
```
## on centre/réduit les données
```{r}
# on centre réduit sauf le CO2
meteoCO2_mean_scaled <- meteoCO2_mean %>%
  select(-day, -CO2_dry_corr_cal) %>%
  scale(center = TRUE, scale = TRUE) %>%
  as.data.frame() 
meteoCO2_mean_scaled$day <- meteoCO2_mean$day
meteoCO2_mean_matin_scaled <- meteoCO2_mean_matin %>%
  select(-day, -CO2_dry_corr_cal) %>%
  scale(center = TRUE, scale = TRUE) %>%
  as.data.frame()
meteoCO2_mean_matin_scaled$day <- meteoCO2_mean_matin$day
meteoCO2_mean_soir_scaled <- meteoCO2_mean_soir %>%
  select(-day, -CO2_dry_corr_cal) %>%
  scale(center = TRUE, scale = TRUE) %>%
  as.data.frame()
meteoCO2_mean_soir_scaled$day <- meteoCO2_mean_soir$day
meteoCO2_mean_DJF_scaled <- meteoCO2_mean_DJF %>%
  select(-day, -CO2_dry_corr_cal) %>%
  scale(center = TRUE, scale = TRUE) %>%
  as.data.frame()
meteoCO2_mean_DJF_scaled$day <- meteoCO2_mean_DJF$day
meteoCO2_mean_matin_DJF_scaled <- meteoCO2_mean_matin_DJF %>%
  select(-day, -CO2_dry_corr_cal) %>%
  scale(center = TRUE, scale = TRUE) %>%
  as.data.frame()
meteoCO2_mean_matin_DJF_scaled$day <- meteoCO2_mean_matin_DJF$day
meteoCO2_mean_soir_DJF_scaled <- meteoCO2_mean_soir_DJF %>%
  select(-day, -CO2_dry_corr_cal) %>%
  scale(center = TRUE, scale = TRUE) %>%
  as.data.frame()
meteoCO2_mean_soir_DJF_scaled$day <- meteoCO2_mean_soir_DJF$day
```

## ACP
# Clustering
## CAH sur Matin DJF scaled mais pas désaisonnalisé
```{r}
figpath2 <- paste0(figpath, "CAH/")
```
```{r}
distance_mat <- dist(meteoCO2_mean_matin_DJF_scaled,"euclidian")
hc <- hclust(distance_mat)

# Plot les distances auxquelles sont aggrégés les clusters
height_data <- data.frame(
  Iteration = 1:length(hc$height),  # Les itérations
  Hauteur = hc$height                # Les hauteurs des clusters à chaque itération
)
ggplot(height_data, aes(x = Iteration, y = Hauteur)) +
  geom_line(color = "darkslateblue") +  # Trace la ligne
  labs(title = "Distance d'aggrégation", x = "Itération", y = "Hauteur") +
  theme_minimal()

if (savefig) {
  ggsave(file.path(figpath2, "dist_complete_CAH_without_PCA_DJF_matin.png"), width = 10, height = 6, bg = "white")
}

b<-cutree(hc, k = 8) # k le nombre de clusters souhaités

suppressPackageStartupMessages(library(dendextend))
avg_dend_obj1 <- as.dendrogram(hc)
ordered_clusters <- b[order.dendrogram(avg_dend_obj1)]

# Colorier les branches du dendrogramme selon les groupes formés par cutree
avg_col_dend1 <- color_branches(avg_dend_obj1, clusters = ordered_clusters)
#suppress labels
avg_col_dend1 <- set_labels(avg_col_dend1, k = 8, h = 20, labels = NA)
#avg_col_dend1 <- color_branches(avg_dend_obj1, k=6, h = 35)
plot(avg_col_dend1, cex.axis = 3, xaxt = "n")

if (savefig) {
  png(file.path(figpath2, "complete_CAH_without_PCA.png"), width = 4000, height = 3000, res = 300)
  plot(avg_col_dend1, cex.axis = 3, xaxt = "n")
  dev.off()  
}
meteoCO2_mean_matin_DJF$cluster <- b
rm(b)
```
```{r}
vars_dict <- list(
  CO2_dry_corr_cal = "CO2 (ppm)",
  t2m = "Température a 2m",
  relative_humidity = "Humidité relative",
  surfacepressure = "Pression de surface",
  ssrd = "Rayonnement solaire",
  windu = "Vent u",
  windv = "Vent v",
  ablh = "Hauteur de la couche limite",
  wd = "Direction du vent",
  ws = "Vitesse du vent"
)
ddff <- uv2ddff(meteoCO2_mean_matin_DJF$windu, meteoCO2_mean_matin_DJF$windv)
meteoCO2_mean_matin_DJF$wd <- ddff$dd
meteoCO2_mean_matin_DJF$ws <- ddff$ff

plot_clustering_results(meteoCO2_mean_matin_DJF, 'cluster', 'complete_CAH_without_PCA', 'completeCH_withoutPCA', vars_dict = vars_dict)
```
# En travaillant sur les jours de vents faibles uniquement
```{r}
# on charge les jours de vents faibles
jours_vent_faible <- read.csv("./data/processed/jours_vent_faible_LCP.csv")
matins_vent_faible <- read.csv("./data/processed/jours_vent_faible_matin_LCP.csv")
soirs_vent_faible <- read.csv("./data/processed/jours_vent_faible_soir_LCP.csv")

jours_vent_faible$date <- as.Date(jours_vent_faible$date)
matins_vent_faible$date <- as.Date(matins_vent_faible$date)
soirs_vent_faible$date <- as.Date(soirs_vent_faible$date)
```
## on refait la classif sur les jours de vents faibles uniquement
```{r}
meteoCO2_mean_matin_DJF_vent_faible <- meteoCO2_mean_matin_DJF %>%
  filter(day %in% matins_vent_faible$date)

meteoCO2_mean_matin_DJF_vent_faible_scaled <- meteoCO2_mean_matin_DJF_vent_faible %>%
  select(-day, -CO2_dry_corr_cal) %>%
  scale(center = TRUE, scale = TRUE) %>%
  as.data.frame()

distance_mat <- dist(meteoCO2_mean_matin_DJF_vent_faible_scaled,"euclidian")
hc <- hclust(distance_mat)

# Plot les distances auxquelles sont aggrégés les clusters
height_data <- data.frame(
  Iteration = 1:length(hc$height),  # Les itérations
  Hauteur = hc$height                # Les hauteurs des clusters à chaque itération
)
ggplot(height_data, aes(x = Iteration, y = Hauteur)) +
  geom_line(color = "darkslateblue") +  # Trace la ligne
  labs(title = "Distance d'aggrégation", x = "Itération", y = "Hauteur") +
  theme_minimal()

if (savefig) {
  ggsave(file.path(figpath2, "dist_complete_CAH_without_PCA_DJF_matin_vent_faible.png"), width = 10, height = 6, bg = "white")
}
b <- cutree(hc, k = 4) # k le nombre de clusters souhaités
avg_dend_obj1 <- as.dendrogram(hc)
ordered_clusters <- b[order.dendrogram(avg_dend_obj1)]
avg_col_dend1 <- color_branches(avg_dend_obj1, clusters = ordered_clusters)
avg_col_dend1 <- set_labels(avg_col_dend1, k = 4, h = 20, labels = NA)
plot(avg_col_dend1, cex.axis = 3, xaxt = "n")

if (savefig) {
  png(file.path(figpath2, "complete_CAH_without_PCA_vent_faible.png"), width = 4000, height = 3000, res = 300)
  plot(avg_col_dend1, cex.axis = 3, xaxt = "n")
  dev.off()  
}
meteoCO2_mean_matin_DJF_vent_faible$cluster <- b
plot_clustering_results(meteoCO2_mean_matin_DJF_vent_faible, 'cluster', 'complete_CAH_without_PCA_vent_faible', 'completeCH_withoutPCA_vent_faible', vars_dict = vars_dict)

```
```{r}
ddff <- uv2ddff(meteoCO2_mean_matin_DJF$windu, meteoCO2_mean_matin_DJF$windv)
meteoCO2_mean_matin_DJF$wd <- ddff$dd
meteoCO2_mean_matin_DJF$ws <- ddff$ff

plot_clustering_results(meteoCO2_mean_matin_DJF_vent_faible, 'cluster', 'complete_CAH_without_PCA_vent_faible', 'completeCH_withoutPCA_vent_faible', vars_dict = vars_dict)
```
## avec les GMM
```{r}
library(mclust)
# on refait la classif sur les jours de vents faibles uniquement
meteoCO2_mean_matin_DJF_vent_faible_scaled <- meteoCO2_mean_matin_DJF_vent_faible %>%
  select(-day, -CO2_dry_corr_cal) %>%
  scale(center = TRUE, scale = TRUE) %>%
  as.data.frame()
gmm_model <- Mclust(meteoCO2_mean_matin_DJF_vent_faible_scaled, G = 6) # G le nombre de clusters souhaités
summary(gmm_model)
meteoCO2_mean_matin_DJF_vent_faible$cluster_gmm <- gmm_model$classification
plot_clustering_results(meteoCO2_mean_matin_DJF_vent_faible, 'cluster_gmm', 'GMM_complete_CAH_without_PCA_vent_faible', 'GMM_completeCH_withoutPCA_vent_faible', vars_dict = vars_dict)
```


