---
title: "compa"
output: html_document
---
```{r setup} 
# on fait en sorte que le wd soit bon aussi quand on exécute chunk by chunk
if (interactive()) {
  setwd(rprojroot::find_rstudio_root_file())
}
```

```{r, results='hide', warnings = FALSE, message= FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(openair)
library(foehnix)
library(metR)
library(ncdf4)
library(patchwork)
# paramètres pour l'exécution du code
savefig = TRUE
```

```{r}
#chargement des fichiers
df_mf <- read.csv("./data/raw/MeteoFrance/LCPMARVAL_20162025.csv", header = TRUE, sep = ",")
figpath = ("./outputs/figures/compaMARobsERA5/")
nc_windu_era5 <- nc_open("./data/raw/ECMWF/MARforcomparison/20222023_MARcoords_ERA5windu.nc")
nc_windv_era5 <- nc_open("./data/raw/ECMWF/MARforcomparison/20222023_MARcoords_ERA5windv.nc")
nc_t2m_era5 <- nc_open("./data/raw/ECMWF/MARforcomparison/20222023_MARcoords_ERA5_t2m.nc")
nc_tp_era5 <- nc_open("./data/raw/ECMWF/MARforcomparison/20222023_MARcoords_ERA5_totalprecipitation.nc")

```

```{r}
# créatrion d'un dataframe avec les deux
# dans df_mf, on sélectionnne MAR
df_mf$DateTime <- as.POSIXct(strptime(as.character(df_mf$AAAAMMJJHH), format = "%Y%m%d%H"), tz = "UTC")
df <- df_mf %>%
  filter(NUM_POSTE == 13054001)%>%
  select(DateTime, FF, DD, T, RR1)
# on prend que 2022 et 2023 pour df
df <- df %>%
  filter(DateTime >= as.POSIXct("2022-01-01") & DateTime < as.POSIXct("2024-01-01"))

time <- ncvar_get(nc_windu_era5, "valid_time") 

# Définir la date de début (1970) pour la conversion de l'heure en date
start_date <- as.POSIXct("1970-01-01 00:00:00", tz = "UTC")
date <- start_date + time

# Définir la date limite (début 2025) car quand on télécharge les données pour l'année en cours, la date de fin diffère
end_date <- as.POSIXct("2025-01-01 00:00:00", tz = "UTC")

# Filtrer les données jusqu'à cette date
valid_indices <- which(date <= end_date)

date <- date[valid_indices]

df_era5 <- data.frame(
  date = ncvar_get(nc_windu_era5, "valid_time")[valid_indices],
  windu_era5 = ncvar_get(nc_windu_era5, "u10")[valid_indices],
  windv_era5 = ncvar_get(nc_windv_era5, "v10")[valid_indices],
  t2m_era5 = ncvar_get(nc_t2m_era5, "t2m")[valid_indices],
  tp_era5 = ncvar_get(nc_tp_era5, "tp")[valid_indices]
)

rm(nc_windu_era5, nc_windv_era5, nc_t2m_era5, nc_tp_era5, time, start_date, end_date, valid_indices)
df_era5$t2m_era5 <- df_era5$t2m_era5 - 273.15  # conversion de Kelvin à Celsius

# on transforme date de secondes en POSIXct
df_era5$date <- as.POSIXct(df_era5$date, origin = "1970-01-01", tz = "UTC")
df_era5 <- df_era5 %>%
  filter(date >= as.POSIXct("2022-01-01") & date < as.POSIXct("2024-01-01"))

df$windu_era5 <- df_era5$windu_era5[match(df$DateTime, df_era5$date)]
df$windv_era5 <- df_era5$windv_era5[match(df$DateTime, df_era5$date)]
df$t2m_era5 <- df_era5$t2m_era5[match(df$DateTime, df_era5$date)]
df$tp_era5 <- df_era5$tp_era5[match(df$DateTime, df_era5$date)]

ddff <- uv2ddff(df$windu_era5, df$windv_era5)
df$DD_era5 <- ddff$dd
df$FF_era5 <- ddff$ff

uv <- ddff2uv(df$DD, df$FF)
df$windu_mf <- uv$u
df$windv_mf <- uv$v
```

```{r}
 # plot as Menut
# on sélectionne trois jours ou plus dans le df
df_3j <- df %>%
  filter(DateTime > as.POSIXct("2023-02-17") & DateTime < as.POSIXct("2023-02-21"))

# on crée une colonne avec les heures dsepuis le début du df
df_3j$heures <- as.numeric(difftime(df_3j$DateTime, min(df_3j$DateTime), units = "hours"))

```

```{r}
breaks_major <- seq(0, max(df_3j$heures), by = 24)

breaks_minor <- seq(0, max(df_3j$heures), by = 6)

xlim_common <- range(df_3j$heures, na.rm = TRUE)
xlim_common <- c(xlim_common[1] - 1, xlim_common[2] + 4)  # ajoute 3h de marge A MODIFIER SI ERREUR GENRE OUTSIDE THE SCALE RANGE


a <- ggplot(df_3j, aes(x = heures, y = 0)) +
  geom_point() +
  geom_segment(aes(xend = heures + windu_mf, yend = windv_mf), y = 0, arrow = arrow()) +
  scale_x_continuous(
    name = NULL,
    limits = xlim_common,
    breaks = breaks_major,
    minor_breaks = breaks_minor,
    labels = NULL
  ) +
  coord_fixed() +
  theme_minimal() +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )

b <- ggplot(df_3j, aes(x = heures, y = 0)) +
  geom_point() +
  geom_segment(aes(xend = heures + windu_era5, yend = windv_era5), y = 0, arrow = arrow()) +
  scale_x_continuous(
    name = NULL,
    limits = xlim_common,
    breaks = breaks_major,
    minor_breaks = breaks_minor,
    labels = function(x) format(min(df_3j$DateTime) + x * 3600,  "%Y-%m-%d %H:%M")
  ) +
  coord_fixed() +
  theme_minimal() +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )
a / b

summary(df_3j$windu_mf)
summary(df_3j$windu_era5)
summary(df_3j$windv_mf)
summary(df_3j$windv_era5)
```

```{r}
rmse_ff <- sqrt(mean((df$FF - df$FF_era5)^2, na.rm = TRUE))
print(paste("RMSE FF:", round(rmse_ff, 2)))
bias_ff <- mean(df$FF - df$FF_era5, na.rm = TRUE)
print(paste("Bias FF:", round(bias_ff, 2)))
rmse_t <- sqrt(mean((df$T - df$t2m_era5)^2, na.rm = TRUE))
print(paste("RMSE T:", round(rmse_t, 2)))
bias_t <- mean(df$T - df$t2m_era5, na.rm = TRUE)
print(paste("Bias T:", round(bias_t, 2)))
```
```{r}
# ça marche pas pour l'instant
#count le nb de jours de pluie pour RR1 et tp sachant que mes données sont horaire du coup summarize par jour (DateTime est en posixct) 
df$Date <- as.Date(df$DateTime)
df_pluie <- df %>%
  group_by(Date) %>%
  summarize(
    pluie_mf = sum(RR1 > 0, na.rm = TRUE),
    pluie_era5 = sum(tp_era5 > 0, na.rm = TRUE)
  )
```

